//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{ 
    public enum GameStatus
    {
        /// <summary>
        /// 未开始
        /// </summary>
        None = 0,
        /// <summary>
        /// 进行中
        /// </summary>
        Progressing = 1,
        /// <summary>
        /// 胜利
        /// </summary>
        Win = 2,
        /// <summary>
        /// 失败
        /// </summary>
        Over = 3,
    }

} 
