//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{ 
    public enum SweetType
    {
        Empty = 0,
        Normal = 1,
        Barrier = 2,
        Row_Clear = 3,
        Column_Clear = 4,
        Rainbow = 5,
        /// <summary>
        /// 标记类型
        /// </summary>
        Count = 6,
    }

} 
